name: cleanup old branches

on:
  push:
    branches: [ "master" ]

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.9
        with:
          repo_token: ${{ github.token }}
          date: '3 months ago'
          dry_run: false
          delete_tags: true
          minimum_tags: 5
          exclude_open_pr_branches: true
