name: cleanup old branches

on: [push]

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    steps:
      - run: git branch -r --merged | grep -v master | sed 's/origin\///' | xargs -n 1 git push --delete origin
      - run: git remote prune origin