name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: multirunsql.exe
            asset_name: multirunsql-windows-amd64

    steps:
    - uses: actions/checkout@v2
    - name: publish
      run: dotnet publish -c release
    - name: upload published to release
      id: create_release
      uses: actions/upload-artifact@v3
      with:
        path: .\appui\bin\Release\net6.0-windows\publish
        name: miltisqlrun-portable
