name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: multirunsql.exe
            asset_name: multirunsql-windows-amd64

    steps:
    - uses: actions/checkout@v2
    - name: publish
      run: dotnet publish -c release
    - name: upload published to release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}-portable
        release_name: Release ${{ github.ref }}
